version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - poney:/data/db
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: max
     # MONGO_INITDB_ROOT_PASSWORD: secret
     # - MONGO_INITIDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env
    
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - gata:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
    - ./env/backend.env
    depends_on:
      - mongodb
  
  #frontend:

volumes:
  poney:
  gata: